-- Canadian region taxonomy for the Gigsii tenant (tenant_id=2).
-- Generated by tools/sql/gen_geo_seed.py; do not edit by hand.
-- Re-runnable: INSERT IGNORE skips rows whose slug already exists.

SET @tid := 2;

INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
VALUES (@tid, NULL, 'country', 'CA', 'Canada', 'canada', 'CA', 56.1304, -106.3468, 5000, 40000000, 0);

-- Provinces and territories
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'ON', 'Ontario', 'ontario', 'CA', 51.2538, -85.3232, 900, 15600000, 0 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'QC', 'Quebec', 'quebec', 'CA', 52.9399, -73.5491, 900, 8800000, 1 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'BC', 'British Columbia', 'british-columbia', 'CA', 53.7267, -127.6476, 900, 5200000, 2 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'AB', 'Alberta', 'alberta', 'CA', 53.9333, -116.5765, 700, 4600000, 3 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'MB', 'Manitoba', 'manitoba', 'CA', 53.7609, -98.8139, 700, 1400000, 4 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'SK', 'Saskatchewan', 'saskatchewan', 'CA', 52.9399, -106.4509, 700, 1200000, 5 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'NS', 'Nova Scotia', 'nova-scotia', 'CA', 44.682, -63.7443, 300, 1000000, 6 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'NB', 'New Brunswick', 'new-brunswick', 'CA', 46.5653, -66.4619, 300, 790000, 7 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'NL', 'Newfoundland and Labrador', 'newfoundland-labrador', 'CA', 53.1355, -57.6604, 800, 525000, 8 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'PE', 'Prince Edward Island', 'prince-edward-island', 'CA', 46.5107, -63.4168, 100, 165000, 9 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'YT', 'Yukon', 'yukon', 'CA', 64.2823, -135.0, 900, 44000, 10 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'NT', 'Northwest Territories', 'northwest-territories', 'CA', 61.2181, -113.5083, 1200, 45000, 11 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'province', 'NU', 'Nunavut', 'nunavut', 'CA', 70.2998, -83.1076, 2000, 39000, 12 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='canada';

-- Cities
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Toronto', 'toronto', 'CA', 43.6532, -79.3832, 35, 2930000, 0 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Ottawa', 'ottawa', 'CA', 45.4215, -75.6972, 30, 1017000, 1 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Mississauga', 'mississauga', 'CA', 43.589, -79.6441, 25, 720000, 2 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Brampton', 'brampton', 'CA', 43.7315, -79.7624, 25, 656000, 3 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Hamilton', 'hamilton', 'CA', 43.2557, -79.8711, 25, 570000, 4 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'London', 'london', 'CA', 42.9849, -81.2453, 20, 423000, 5 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Markham', 'markham', 'CA', 43.8561, -79.337, 20, 338000, 6 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Vaughan', 'vaughan', 'CA', 43.8361, -79.4983, 20, 324000, 7 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Kitchener', 'kitchener', 'CA', 43.4516, -80.4925, 20, 256000, 8 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Windsor', 'windsor', 'CA', 42.3149, -83.0364, 20, 229000, 9 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Oakville', 'oakville', 'CA', 43.4675, -79.6877, 15, 213000, 10 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Burlington', 'burlington', 'CA', 43.3255, -79.799, 15, 186000, 11 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Oshawa', 'oshawa', 'CA', 43.8971, -78.8658, 15, 175000, 12 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='ontario';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Montreal', 'montreal', 'CA', 45.5017, -73.5673, 30, 1763000, 13 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Quebec City', 'quebec-city', 'CA', 46.8139, -71.208, 25, 542000, 14 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Laval', 'laval', 'CA', 45.6066, -73.7124, 20, 438000, 15 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Gatineau', 'gatineau', 'CA', 45.4765, -75.7013, 20, 291000, 16 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Longueuil', 'longueuil', 'CA', 45.5371, -73.5119, 15, 254000, 17 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Sherbrooke', 'sherbrooke', 'CA', 45.4042, -71.8929, 15, 173000, 18 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Saguenay', 'saguenay', 'CA', 48.4275, -71.0686, 20, 144000, 19 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Trois-Rivieres', 'trois-rivieres', 'CA', 46.3432, -72.5432, 15, 139000, 20 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='quebec';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Vancouver', 'vancouver', 'CA', 49.2827, -123.1207, 30, 675000, 21 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Surrey', 'surrey', 'CA', 49.1913, -122.849, 25, 568000, 22 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Burnaby', 'burnaby', 'CA', 49.2488, -122.9805, 15, 249000, 23 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Richmond', 'richmond', 'CA', 49.1666, -123.1336, 15, 209000, 24 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Victoria', 'victoria', 'CA', 48.4284, -123.3656, 15, 92000, 25 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Kelowna', 'kelowna', 'CA', 49.888, -119.496, 20, 144000, 26 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Abbotsford', 'abbotsford', 'CA', 49.0504, -122.3045, 15, 153000, 27 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='british-columbia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Calgary', 'calgary', 'CA', 51.0447, -114.0719, 30, 1306000, 28 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='alberta';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Edmonton', 'edmonton', 'CA', 53.5461, -113.4938, 30, 1010000, 29 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='alberta';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Red Deer', 'red-deer', 'CA', 52.2681, -113.8112, 15, 100000, 30 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='alberta';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Lethbridge', 'lethbridge', 'CA', 49.6956, -112.8451, 15, 99000, 31 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='alberta';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Winnipeg', 'winnipeg', 'CA', 49.8951, -97.1384, 30, 749000, 32 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='manitoba';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Brandon', 'brandon', 'CA', 49.8489, -99.9501, 15, 51000, 33 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='manitoba';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Saskatoon', 'saskatoon', 'CA', 52.1332, -106.67, 20, 273000, 34 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='saskatchewan';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Regina', 'regina', 'CA', 50.4452, -104.6189, 20, 226000, 35 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='saskatchewan';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Halifax', 'halifax', 'CA', 44.6488, -63.5752, 30, 440000, 36 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='nova-scotia';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Moncton', 'moncton', 'CA', 46.0878, -64.7782, 15, 79000, 37 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='new-brunswick';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Saint John', 'saint-john', 'CA', 45.2733, -66.0633, 15, 69000, 38 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='new-brunswick';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Fredericton', 'fredericton', 'CA', 45.9636, -66.6431, 15, 63000, 39 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='new-brunswick';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'St. John''s', 'st-johns', 'CA', 47.5615, -52.7126, 20, 110000, 40 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='newfoundland-labrador';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Charlottetown', 'charlottetown', 'CA', 46.2382, -63.1311, 10, 38000, 41 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='prince-edward-island';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Whitehorse', 'whitehorse', 'CA', 60.7212, -135.0568, 15, 28000, 42 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='yukon';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Yellowknife', 'yellowknife', 'CA', 62.454, -114.3718, 15, 20000, 43 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='northwest-territories';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'city', NULL, 'Iqaluit', 'iqaluit', 'CA', 63.7467, -68.517, 10, 8000, 44 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='nunavut';

-- Toronto neighborhoods (flagship Gigsii market)
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Downtown Toronto', 'downtown-toronto', 'CA', 43.65, -79.3833, 3, NULL, 0 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Financial District', 'financial-district', 'CA', 43.6483, -79.3815, 2, NULL, 1 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Entertainment District', 'entertainment-district', 'CA', 43.645, -79.39, 2, NULL, 2 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'The Annex', 'annex', 'CA', 43.67, -79.405, 2, NULL, 3 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Yorkville', 'yorkville', 'CA', 43.6711, -79.3897, 2, NULL, 4 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Kensington Market', 'kensington-market', 'CA', 43.6547, -79.4023, 2, NULL, 5 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Liberty Village', 'liberty-village', 'CA', 43.6385, -79.4225, 2, NULL, 6 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'King West', 'king-west', 'CA', 43.644, -79.4, 2, NULL, 7 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Queen West', 'queen-west', 'CA', 43.647, -79.418, 2, NULL, 8 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Leslieville', 'leslieville', 'CA', 43.6646, -79.3392, 2, NULL, 9 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Riverside', 'riverside', 'CA', 43.6594, -79.3502, 2, NULL, 10 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'The Beaches', 'the-beaches', 'CA', 43.6716, -79.2941, 3, NULL, 11 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'High Park', 'high-park', 'CA', 43.6465, -79.4637, 3, NULL, 12 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Roncesvalles', 'roncesvalles', 'CA', 43.6481, -79.4486, 2, NULL, 13 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'The Junction', 'the-junction', 'CA', 43.666, -79.469, 2, NULL, 14 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Etobicoke', 'etobicoke', 'CA', 43.6205, -79.5132, 8, NULL, 15 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Scarborough', 'scarborough', 'CA', 43.7764, -79.2318, 12, NULL, 16 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'North York', 'north-york', 'CA', 43.7615, -79.4111, 8, NULL, 17 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'East York', 'east-york', 'CA', 43.6911, -79.3279, 4, NULL, 18 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';
INSERT IGNORE INTO wp_mercato_geo_regions (tenant_id, parent_id, type, code, name, slug, country_code, latitude, longitude, radius_km, population, sort_order)
SELECT @tid, region_id, 'neighborhood', NULL, 'Midtown Toronto', 'midtown-toronto', 'CA', 43.7065, -79.3984, 4, NULL, 19 FROM wp_mercato_geo_regions WHERE tenant_id=@tid AND slug='toronto';

-- Verify
SELECT type, COUNT(*) AS rows FROM wp_mercato_geo_regions WHERE tenant_id=@tid GROUP BY type ORDER BY FIELD(type, 'country','province','city','neighborhood');
