CREATE TABLE IF NOT EXISTS `{prefix}mercato_service_requests` (
  `request_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `client_user_id` BIGINT UNSIGNED DEFAULT NULL,
  `category_id` BIGINT UNSIGNED DEFAULT NULL,
  `title` VARCHAR(160) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `city` VARCHAR(120) DEFAULT NULL,
  `region` VARCHAR(120) DEFAULT NULL,
  `country` CHAR(2) DEFAULT NULL,
  `latitude` DECIMAL(10,7) DEFAULT NULL,
  `longitude` DECIMAL(10,7) DEFAULT NULL,
  `budget_min_minor` BIGINT DEFAULT NULL,
  `budget_max_minor` BIGINT DEFAULT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'USD',
  `bid_mode` ENUM('sealed_bid','open_auction') NOT NULL DEFAULT 'sealed_bid',
  `status` ENUM('open','awarded','cancelled','expired') NOT NULL DEFAULT 'open',
  `expires_at` DATETIME(3) DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`request_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`, `created_at`),
  KEY `idx_category` (`tenant_id`, `category_id`, `status`),
  KEY `idx_geo` (`tenant_id`, `latitude`, `longitude`)
) {charset_collate};

CREATE TABLE IF NOT EXISTS `{prefix}mercato_service_bids` (
  `bid_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `request_id` BIGINT UNSIGNED NOT NULL,
  `vendor_id` BIGINT UNSIGNED NOT NULL,
  `amount_minor` BIGINT NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'USD',
  `message` TEXT DEFAULT NULL,
  `estimated_start_at` DATETIME(3) DEFAULT NULL,
  `estimated_duration_minutes` INT DEFAULT NULL,
  `status` ENUM('submitted','withdrawn','accepted','rejected') NOT NULL DEFAULT 'submitted',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`bid_id`),
  UNIQUE KEY `uk_request_vendor` (`tenant_id`, `request_id`, `vendor_id`),
  KEY `idx_request` (`tenant_id`, `request_id`, `amount_minor`),
  KEY `idx_vendor` (`tenant_id`, `vendor_id`, `created_at`)
) {charset_collate};
