apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpress.secretRef }}
  labels:
{{ include "mercato.labels" . | indent 4 }}
type: Opaque
stringData:
  WORDPRESS_DB_USER: "replace_me"
  WORDPRESS_DB_PASSWORD: "replace_me"
  MERCATO_DATABASE_DSN: "replace_me"
  MERCATO_TEST_API_SECRET: "replace_me"
  STRIPE_SECRET_KEY: "replace_me"
  STRIPE_WEBHOOK_SECRET: "replace_me"
  SENDGRID_API_KEY: "replace_me"
  AWS_ACCESS_KEY_ID: "replace_me"
  AWS_SECRET_ACCESS_KEY: "replace_me"
  MERCATO_METRICS_TOKEN: "replace_me"
